version: '2'

services:

  web:
    image: node:latest
    build: .
    working_dir: /usr/src/shortly-app/shortly-deploy
    volumes:
      - ./:/usr/src/shortly-app/shortly-deploy
    ports:
      - "80:4568"
    depends_on:
      - db
    environment:
      PORT: 4568
      DB_HOST: 'mongo'
    networks:
      - all

  db:
    image: mongo
    command: mongod --smallfiles
    networks:
      - all

networks:
  all:
