version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: "--smallfiles --logpath=/dev/null"
  shortly-app:
    build: shortly-app
    image: shortly-app
    command: /usr/src/shortly-app/shortly-deploy/node_modules/grunt/bin/grunt server-prod
    volumes:
      - /usr/src/shortly-app/shortly-deploy
    ports:
      - "4568:4568"
    links:
      - db
    environment:
      PORT: 4568
